/* ShopJoy BO - Vue 컴포넌트 등록 (boAppBase.js 에서 분리) */
window.boRegisterComponents = function (app) {
  return app
    /* ── pages/base/ ── */
    .component('BoError404', window.boError404)
    .component('BoError401', window.boError401)
    .component('BoError500', window.boError500)
    /* ── components/disp/ (전시 핵심 컴포넌트) ── */
    .component('DispX01Ui', window.DispX01Ui)
    .component('DispX02Area', window.DispX02Area)
    .component('DispX03Panel', window.DispX03Panel || { template: '<div/>' })
    .component('DispX04Widget', window.DispX04Widget || { template: '<div/>' })
    .component('CoBarcodeWidget', window.CoBarcodeWidget || { template: '<div/>' })
    .component('CoCountdownWidget', window.CoCountdownWidget || { template: '<div/>' })
    /* ── components/comp/ (공통 컴포넌트) ── */
    .component('CoEchartComp', window.CoEchartComp)
    .component('CoEchart', window.CoEchartComp)
    .component('CoNotiBell', window.CoNotiBell)
    .component('BaseAttachGrp', window.BaseAttachGrp)
    .component('BaseAttachOne', window.BaseAttachOne)
    .component('BaseHtmlEditor', window.BaseHtmlEditor)
    .component('BaseTossPayWidget', window.BaseTossPayWidget)
    /* ── pages/bo/ (공통) ── */
    .component('ZdSimulNotiMng', window.ZdSimulNotiMng)
    .component('BoRefModal', window.BoRefModal)
    .component('BoExcelUploadModal', window.BoExcelUploadModal)
    /* ── pages/bo/ec/ — 회원 ── */
    .component('MbMemberMng', window.MbMemberMng)
    .component('MbMemberDtl', window.MbMemberDtl)
    .component('MbMemberHist', window.MbMemberHist)
    .component('MbMemGradeMng', window.MbMemGradeMng)
    .component('MbMemGroupMng', window.MbMemGroupMng)
    /* ── pages/bo/ec/ — 상품 ── */
    .component('PdProdMng', window.PdProdMng)
    .component('PdProdDtl', window.PdProdDtl)
    .component('PdProdHist', window.PdProdHist)
    .component('PdDlivTmpltMng', window.PdDlivTmpltMng)
    .component('PdSingleProdMng', window.PdSingleProdMng)
    .component('PdOptionProdMng', window.PdOptionProdMng)
    .component('PdGroupProdMng', window.PdGroupProdMng)
    .component('PdSetProdMng', window.PdSetProdMng)
    .component('PdGiftProdMng', window.PdGiftProdMng)
    .component('PdReviewMng', window.PdReviewMng)
    .component('PdQnaMng', window.PdQnaMng)
    .component('PdRestockNotiMng', window.PdRestockNotiMng)
    .component('PdTagMng', window.PdTagMng)
    /* ── pages/co/ec/ — 주문 칸반 ── */
    .component('OdOrderKanban', window.OdOrderKanban)
    /* ── pages/bo/ec/ — 주문 ── */
    .component('OdOrderMng', window.OdOrderMng)
    .component('OdOrderItemMng', window.OdOrderItemMng)
    .component('OdOrderItemDtl', window.OdOrderItemDtl)
    .component('OdOrderDtl', window.OdOrderDtl)
    .component('OdOrderHist', window.OdOrderHist)
    /* ── pages/bo/ec/ — 클레임 ── */
    .component('OdClaimCalcModal', window.OdClaimCalcModal)
    .component('OdClaimMng', window.OdClaimMng)
    .component('OdClaimDtl', window.OdClaimDtl)
    .component('OdClaimHist', window.OdClaimHist)
    /* ── pages/bo/ec/ — 배송 ── */
    .component('OdDlivMng', window.OdDlivMng)
    .component('OdDlivDtl', window.OdDlivDtl)
    .component('OdDlivHist', window.OdDlivHist)
    .component('OdCartMng', window.OdCartMng)
    /* ── pages/bo/ec/ — 쿠폰/캐쉬 ── */
    .component('PmCouponMng', window.PmCouponMng)
    .component('PmCouponDtl', window.PmCouponDtl)
    .component('PmCacheMng', window.PmCacheMng)
    .component('PmCacheDtl', window.PmCacheDtl)
    /* ── pages/bo/ec/ — 전시관리 ── */
    .component('DpDispPanelMng', window.DpDispPanelMng)
    .component('DpDispPanelDtl', window.DpDispPanelDtl)
    .component('DpDispAreaMng', window.DpDispAreaMng)
    .component('DpDispAreaDtl', window.DpDispAreaDtl)
    .component('DpDispUiMng', window.DpDispUiMng)
    .component('DpDispUiDtl', window.DpDispUiDtl)
    .component('DpDispWidgetMng', window.DpDispWidgetMng)
    .component('DpDispWidgetDtl', window.DpDispWidgetDtl)
    .component('DpDispUiPreview', window.DpDispUiPreview)
    .component('DpDispPanelPreview', window.DpDispPanelPreview)
    .component('DpDispWidgetPreview', window.DpDispWidgetPreview)
    .component('DpDispAreaPreview', window.DpDispAreaPreview)
    .component('DpDispWidgetLibMng', window.DpDispWidgetLibMng)
    .component('DpDispWidgetLibDtl', window.DpDispWidgetLibDtl)
    .component('DpDispWidgetLibPreview', window.DpDispWidgetLibPreview)
    /* ── pages/bo/ec/ — 카테고리 ── */
    .component('PdCategoryMng', window.PdCategoryMng)
    .component('PdCategoryDtl', window.PdCategoryDtl)
    .component('PdCategoryProdMng', window.PdCategoryProdMng)
    .component('PdOptCodeMngPage', window.PdOptCodeMngPage)
    /* ── pages/bo/ec/ — 이벤트/공지 ── */
    .component('PmEventMng', window.PmEventMng)
    .component('PmEventDtl', window.PmEventDtl)
    .component('PmPlanMng', window.PmPlanMng)
    .component('PmPlanDtl', window.PmPlanDtl)
    .component('PmDiscntMng', window.PmDiscntMng)
    .component('PmDiscntDtl', window.PmDiscntDtl)
    .component('PmSaveMng', window.PmSaveMng)
    .component('PmSaveDtl', window.PmSaveDtl)
    .component('PmGiftMng', window.PmGiftMng)
    .component('PmGiftDtl', window.PmGiftDtl)
    .component('PmVoucherMng', window.PmVoucherMng)
    .component('PmVoucherDtl', window.PmVoucherDtl)
    /* ── pages/bo/ec/st/ — 정산관리 ── */
    .component('StConfigMng', window.StConfigMng)
    .component('StRawMng', window.StRawMng)
    .component('StSettleAdjMng', window.StSettleAdjMng)
    .component('StSettleEtcAdjMng', window.StSettleEtcAdjMng)
    .component('StSettleCloseMng', window.StSettleCloseMng)
    .component('StSettlePayMng', window.StSettlePayMng)
    .component('StStatusMng', window.StStatusMng)
    .component('StReconOrderMng', window.StReconOrderMng)
    .component('StReconPayMng', window.StReconPayMng)
    .component('StReconClaimMng', window.StReconClaimMng)
    .component('StReconVendorMng', window.StReconVendorMng)
    .component('StErpGenMng', window.StErpGenMng)
    .component('StErpViewMng', window.StErpViewMng)
    .component('StErpReconMng', window.StErpReconMng)
    .component('CmNoticeMng', window.CmNoticeMng)
    .component('CmNoticeDtl', window.CmNoticeDtl)
    .component('CmFaqMng', window.CmFaqMng)
    .component('CmFaqDtl', window.CmFaqDtl)
    .component('CmDashboardMng', window.CmDashboardMng)
    .component('CmDashboardItemMng', window.CmDashboardItemMng)
    .component('CmDashboardLayoutMng', window.CmDashboardLayoutMng)
    .component('CmDashboardMyMng', window.CmDashboardMyMng)
    .component('CmDashboardMenuMng', window.CmDashboardMenuMng)
    .component('CmDashboardSysMenuMng', window.CmDashboardSysMenuMng)
    .component('CmPopupMng', window.CmPopupMng)
    /* ── pages/bo/ec/ — 채팅/고객 ── */
    .component('CmChattMng', window.CmChattMng)
    .component('CmChattDtl', window.CmChattDtl)
    .component('CmChattKanban', window.CmChattKanban)
    .component('MbCustInfoMng', window.MbCustInfoMng)
    /* ── pages/bo/sy/ — 대시보드 ── */
    .component('SyDashboardMng', window.SyDashboardMng)
    .component('DashboardBoAppMonitor', window.DashboardBoAppMonitor)
    .component('DashboardBoEc01', window.DashboardBoEc01)
    .component('DashboardBoEc02', window.DashboardBoEc02)
    .component('DashboardBoEc03', window.DashboardBoEc03)
    /* ── pages/bo/sy/ — 사용자/권한/조직 ── */
    .component('SyUserMng', window.SyUserMng)
    .component('SyUserDtl', window.SyUserDtl)
    .component('SyDeptMng', window.SyDeptMng)
    .component('SyMenuMng', window.SyMenuMng)
    .component('SyRoleMng', window.SyRoleMng)
    /* ── pages/bo/sy/ — 사이트/코드/브랜드 ── */
    .component('SySiteMng', window.SySiteMng)
    .component('SySiteDtl', window.SySiteDtl)
    .component('SyCodeMng', window.SyCodeMng)
    .component('SyCodeDtl', window.SyCodeDtl)
    .component('SyBrandMng', window.SyBrandMng)
    /* ── pages/bo/sy/ — 템플릿/업체/첨부 ── */
    .component('SyTemplateMng', window.SyTemplateMng)
    .component('SyTemplateDtl', window.SyTemplateDtl)
    .component('SyVendorMng', window.SyVendorMng)
    .component('SyVendorUserMng', window.SyVendorUserMng)
    .component('SyVendorInfoMng', window.SyVendorInfoMng)
    .component('SyVendorDtl', window.SyVendorDtl)
    .component('SyAttachMng', window.SyAttachMng)
    /* ── pages/bo/sy/ — 배치 ── */
    .component('SyBatchMng', window.SyBatchMng)
    .component('SyBatchDtl', window.SyBatchDtl)
    .component('SyBatchHist', window.SyBatchHist)
    /* ── pages/bo/sy/ — 알림/게시판/문의 ── */
    .component('SyAlarmMng', window.SyAlarmMng)
    .component('SyPropMng', window.SyPropMng)
    .component('SyPathMng', window.SyPathMng)
    .component('SyI18nMng', window.SyI18nMng)
    .component('BoPager', window.BoPager)
    .component('BoTabBar', window.BoTabBar)
    .component('BoPathTree', window.BoPathTree)
    .component('BoPathPickField', window.BoPathPickField)
    .component('BoPathTreeNode', window.BoPathTreeNode)
    .component('BoCategoryTree', window.BoCategoryTree)
    .component('BoMultiCheckSelect', window.BoMultiCheckSelect)
    .component('BoDateTimePicker', window.BoDateTimePicker)
    .component('BoPage', window.BoPage)
    .component('BoContainer', window.BoContainer)
    .component('BoSearchArea', window.BoSearchArea)
    .component('BoFormArea', window.BoFormArea)
    .component('BoGrid', window.BoGrid)
    .component('BoGridCrud', window.BoGridCrud)
    .component('BoGroupTable', window.BoGroupTable)
    .component('BoStatRow', window.BoStatRow)
    .component('BoPathTreeCard', window.BoPathTreeCard)
    .component('BoMenuTree', window.BoMenuTree)
    .component('BoMenuTreeCard', window.BoMenuTreeCard)
    .component('BoLocalTreeCard', window.BoLocalTreeCard)
    .component('BoModal', window.BoModal)
    .component('BoExcelDownModal', window.BoExcelDownModal)
    .component('BoCmPopupModal', window.BoCmPopupModal)
    .component('BoAddrSearchModal', window.BoAddrSearchModal)
    .component('BoCronModal', window.BoCronModal)
    .component('BoTreeSelectorModal', window.BoTreeSelectorModal)
    .component('BoRowCancelDelete', window.BoRowCancelDelete)
    .component('BoRoleSelectModal', window.BoRoleSelectModal)
    .component('BoPathParentSelector', window.BoPathParentSelector)
    .component('PdReviewStatusModal', window.PdReviewStatusModal)
    .component('BoPropTreeNode', window.BoPropTreeNode)
    .component('SyAlarmDtl', window.SyAlarmDtl)
    .component('SyBbmMng', window.SyBbmMng)
    .component('SyBbmDtl', window.SyBbmDtl)
    .component('SyBbsMng', window.SyBbsMng)
    .component('SyBbsDtl', window.SyBbsDtl)
    .component('SyContactMng', window.SyContactMng)
    .component('SyContactDtl', window.SyContactDtl)
    .component('CmBlogMng', window.CmBlogMng)
    /* ── components/modals/ — 인증 모달 ── */
    .component('AuthLoginModal', window.AuthLoginModal)
    .component('CoExtHelpModal', window.CoExtHelpModal || { template: '<div/>' })
    .component('AuthPwChangeModal', window.AuthPwChangeModal)
    .component('AuthUserPickModal', window.AuthUserPickModal)
    .component('AuthProfileModal', window.AuthProfileModal)
    /* ── components/modals/ — 도움말 모달 ── */
    .component('HelpBoModal', window.HelpBoModal)
    /* ── components/modals/ — 트리 모달 ── */
    .component('BoDeptTreeNode', window.BoDeptTreeNode)
    /* ── components/modals/ — 미리보기/전송 모달 ── */
    .component('DispPreviewModal', window.DispPreviewModal || { template: '<div/>' })
    .component('RowPickModal', window.RowPickModal || { template: '<div/>' })
    .component('TemplatePreviewModal', window.TemplatePreviewModal)
    .component('TemplateSendModal', window.TemplateSendModal)
    .component('SyMemberLoginHist', window.SyMemberLoginHist)
    .component('SyUserLoginHist', window.SyUserLoginHist)
    .component('SyExceldownMng', window.SyExceldownMng)
    .component('SyApiLogMng', window.SyApiLogMng)
    .component('SySendMsgLogMng', window.SySendMsgLogMng)
    .component('SyPostman', window.SyPostman)
    /* ── comp — 개발도구 공통 그리드 ── */
    .component('BoZdYmlGrid',     window.BoZdYmlGrid)
    .component('BoZdSyPropGrid',  window.BoZdSyPropGrid)
    /* ── pages/bo/zd/ — 개발도구 ── */
    .component('ZdInfDashboard', window.ZdInfDashboard)
    .component('ZdStore', window.ZdStore)
    .component('ZdLocalStorage', window.ZdLocalStorage)
    .component('ZdTestSnsLoginKakao',  window.ZdTestSnsLoginKakao)
    .component('ZdTestSnsLoginGoogle', window.ZdTestSnsLoginGoogle)
    .component('ZdTestPayTossWidget',  window.ZdTestPayTossWidget)
    .component('ZdTestPayTossBrandpay', window.ZdTestPayTossBrandpay)
    .component('ZdTestPayKakaopay',    window.ZdTestPayKakaopay)
    .component('ZdTestPayNaverpay',    window.ZdTestPayNaverpay)
    .component('ZdTestMapKakao',       window.ZdTestMapKakao)
    .component('ZdTestMapNaver',       window.ZdTestMapNaver)
    .component('ZdTestMapGoogle',      window.ZdTestMapGoogle)
    .component('ZdTestMailSmtp',       window.ZdTestMailSmtp)
    .component('ZdTestSms',            window.ZdTestSms)
    .component('ZdTestPushAlimFcm',          window.ZdTestPushAlimFcm)
    .component('ZdTestPushAlimApns',         window.ZdTestPushAlimApns)
    .component('ZdTestSnsLoginNaver',        window.ZdTestSnsLoginNaver)
    .component('ZdTestAiChatbot',            window.ZdTestAiChatbot)
    .component('ZdTestChattingKakaoChannel', window.ZdTestChattingKakaoChannel)
    .component('ZdTestShareKakao',           window.ZdTestShareKakao)
    .component('ZdTestChattingWebSocket',    window.ZdTestChattingWebSocket)
    .component('ZdTestAppMsgSendReceiv',     window.ZdTestAppMsgSendReceiv)
    /* ── pages/bo/zd/ — 시뮬레이션 공통 + 도메인 ── */
    .component('ZdSimulControlPanel',  window.ZdSimulControlPanel)
    .component('ZdSimulLogPanel',      window.ZdSimulLogPanel)
    .component('ZdSimulPreviewModal',  window.ZdSimulPreviewModal)
    .component('ZdPreviewTable',       window.ZdPreviewTable)
    .component('ZdSimulMemberMng',    window.ZdSimulMemberMng)
    .component('ZdSimulCouponMng',  window.ZdSimulCouponMng)
    .component('ZdSimulDiscntMng',  window.ZdSimulDiscntMng)
    .component('ZdSimulSaveMng',    window.ZdSimulSaveMng)
    .component('ZdSimulPlanMng',    window.ZdSimulPlanMng)
    .component('ZdSimulEventMng',   window.ZdSimulEventMng)
    .component('ZdSimulProdMng',    window.ZdSimulProdMng)
    .component('ZdSimulOrderMng',   window.ZdSimulOrderMng)
    .component('ZdSimulClaimMng',   window.ZdSimulClaimMng)
    .component('ZdSimulKanbanMng',  window.ZdSimulKanbanMng)
    .component('ZdSimulSettleMng',  window.ZdSimulSettleMng)
    .component('ZdSimulUserMng',    window.ZdSimulUserMng)
    .component('ZdSimulVendorMng',  window.ZdSimulVendorMng)
    .component('ZdSimulVoucherMng', window.ZdSimulVoucherMng)
    .component('ZdSimulLogMng',     window.ZdSimulLogMng);
};
