#!/usr/bin/env node
/**
 * Capacitor 환경 적용 스크립트 (FO 앱).
 *
 * 사용법:
 *   node scripts/set-env.js local    # → .env.local 적용
 *   node scripts/set-env.js dev      # → .env.dev 적용
 *   node scripts/set-env.js prod     # → .env.prod 적용
 *
 * 동작:
 *   1) .env.{target} 파일 로드
 *   2) .env.{target}.local 이 있으면 머지 (운영 비밀 오버라이드 — git 무시)
 *   3) capacitor.config.ts 의 server.url / cleartext / androidScheme 갱신
 *   4) www/env.js 자동 생성 — 웹 코드에서 window.__APP_ENV__ 로 접근
 *
 * 우선순위 (뒤가 우선):
 *   .env.{target}  →  .env.{target}.local  →  결과
 *
 * package.json 의 scripts 가 본 스크립트를 호출:
 *   "config:local": "node scripts/set-env.js local"
 *   "android:dev":  "npm run sync:dev && npx cap run android"
 *   "sync:dev":     "npm run config:dev && npx cap sync"
 */
const fs = require('fs');
const path = require('path');

/** 명령행 인자 → local | dev | prod. */
const TARGET = (process.argv[2] || 'local').toLowerCase();

/** 본 스크립트 (`scripts/`) 의 부모 디렉토리 = 앱 프로젝트 루트. */
const ROOT = path.resolve(__dirname, '..');

if (!['local', 'dev', 'prod'].includes(TARGET)) {
  console.error(`[set-env] 알 수 없는 환경: ${TARGET}. (local | dev | prod)`);
  process.exit(1);
}

/**
 * .env 형식 파일을 단순 KEY=VALUE 파서로 로드.
 * 따옴표(`"`, `'`) 자동 제거. 라인 시작 `#` 은 주석.
 *
 * @param {string} filename - 파일명 (ROOT 기준 상대경로).
 * @returns {Object<string, string>} 파일 미존재 시 빈 객체.
 */
function loadEnvFile(filename) {
  const filePath = path.join(ROOT, filename);
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, 'utf8');
  const env = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;     // 빈 줄 / 주석 무시.
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;                              // = 없으면 무시.
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    // 따옴표 제거 (`"value"`, `'value'`).
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

// ───── 1) 환경 파일 로드 + 머지 ─────
const baseEnv = loadEnvFile(`.env.${TARGET}`);
const localOverride = loadEnvFile(`.env.${TARGET}.local`);   // 운영 비밀 (git 무시).
const env = { ...baseEnv, ...localOverride };                 // 뒤가 우선.

if (Object.keys(env).length === 0) {
  console.error(`[set-env] .env.${TARGET} 파일을 찾을 수 없거나 비어있습니다.`);
  process.exit(1);
}

// ───── 2) capacitor.config.ts 갱신 ─────
const cfgPath = path.join(ROOT, 'capacitor.config.ts');
let src = fs.readFileSync(cfgPath, 'utf8');

/** WebView 가 로드할 운영/개발/로컬 URL. */
const url = env.BASE_URL || 'http://10.0.2.2:5501';

/** HTTP 허용 여부 (운영은 false 강제 권장). */
const cleartext = env.CLEARTEXT === 'true';

/** Android scheme — `cleartext: true` 면 자동으로 `http`. */
const androidScheme = env.ANDROID_SCHEME || (cleartext ? 'http' : 'https');

// 정규식으로 server.url / cleartext / androidScheme 라인 치환.
src = src.replace(/url:\s*'[^']*'/, `url: '${url}'`);
src = src.replace(/cleartext:\s*(true|false)/, `cleartext: ${cleartext}`);
src = src.replace(/androidScheme:\s*'[^']*'/, `androidScheme: '${androidScheme}'`);

fs.writeFileSync(cfgPath, src, 'utf8');

// ───── 3) www/env.js 자동 생성 ─────
// 웹 코드에서 `window.__APP_ENV__.BASE_URL` / `window.__APP_ENV_NAME__` 접근 가능.
const wwwEnvPath = path.join(ROOT, 'www', 'env.js');
const wwwEnv = `// AUTO-GENERATED by scripts/set-env.js — do not edit
window.__APP_ENV__ = ${JSON.stringify(env, null, 2)};
window.__APP_ENV_NAME__ = '${TARGET}';
`;
fs.writeFileSync(wwwEnvPath, wwwEnv, 'utf8');

// ───── 4) 결과 출력 (운영 검증용) ─────
console.log(`[set-env] ${TARGET.toUpperCase()} 적용 완료`);
console.log(`         APP_NAME       = ${env.APP_NAME || '(unset)'}`);
console.log(`         BASE_URL       = ${url}`);
console.log(`         CLEARTEXT      = ${cleartext}`);
console.log(`         ANDROID_SCHEME = ${androidScheme}`);
console.log(`         (loaded from   .env.${TARGET}${fs.existsSync(path.join(ROOT, '.env.' + TARGET + '.local')) ? ' + .env.' + TARGET + '.local' : ''})`);
console.log(`         (www/env.js    ${Object.keys(env).length} keys)`);
