-- md_sg_stack 샘플 데이터 — 소스젠 [소스 생성] 팝오버 카탈로그 22종 초기 시드

INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557433963', 'SITE000001', 'SITE000001', 'BACKEND', 'Backend (JPA)', 'backend_jpa/', 'v1,v2,v3', 'v1', 1, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557437461', 'SITE000001', 'SITE000001', 'BACKEND', 'Backend (MyBatis)', 'backend_mybatis/', 'v1,v2,v3', 'v1', 2, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557433187', 'SITE000001', 'SITE000001', 'BACKEND', 'Backend (Python)', 'backend_python/', 'v1,v2,v3', 'v1', 3, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557433826', 'SITE000001', 'SITE000001', 'BACKEND', 'Backend (C# EF Core)', 'backend_csharp_efcore/', 'v1,v2,v3', 'v1', 4, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557433363', 'SITE000001', 'SITE000001', 'BACKEND', 'Backend (C# Dapper)', 'backend_csharp_dapper/', 'v1,v2,v3', 'v1', 5, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557437667', 'SITE000001', 'SITE000001', 'BACKEND', 'Backend (NestJS 10)', 'backend_nestjs/', 'v1,v2,v3', 'v1', 6, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557432119', 'SITE000001', 'SITE000001', 'BACKEND', 'Backend (Express 4)', 'backend_expressjs/', 'v1,v2,v3', 'v1', 7, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557433827', 'SITE000001', 'SITE000001', 'FRONTEND', 'Vue3 CDN (with common)', 'frontend_vue3cdn_with_common/', 'v1,v2,v3', 'v1', 1, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557439243', 'SITE000001', 'SITE000001', 'FRONTEND', 'Vue3 CDN (standalone)', 'frontend_vue3cdn_standalone/', 'v1,v2,v3', 'v1', 2, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557436988', 'SITE000001', 'SITE000001', 'FRONTEND', 'Vue3 SFC', 'frontend_vue3/', 'v1,v2,v3', 'v1', 3, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557434201', 'SITE000001', 'SITE000001', 'FRONTEND', 'React', 'frontend_react/', 'v1,v2,v3', 'v1', 4, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557438240', 'SITE000001', 'SITE000001', 'FRONTEND', 'React CDN (standalone)', 'frontend_react_cdn_standalone/', 'v1,v2,v3', 'v1', 5, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557433485', 'SITE000001', 'SITE000001', 'FRONTEND', 'Svelte', 'frontend_svelte/', 'v1,v2,v3', 'v1', 6, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557438954', 'SITE000001', 'SITE000001', 'FRONTEND', 'Svelte CDN (standalone)', 'frontend_svelte_cdn_standalone/', 'v1,v2,v3', 'v1', 7, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557435607', 'SITE000001', 'SITE000001', 'FRONTEND', 'PyScript CDN (standalone)', 'frontend_pyscript_cdn_standalone/', 'v1,v2,v3', 'v1', 8, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557431943', 'SITE000001', 'SITE000001', 'MOBILE', 'Flutter (Mobile)', 'frontend_flutter/', 'v1,v2,v3', 'v1', 1, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557437606', 'SITE000001', 'SITE000001', 'MOBILE', 'React Native (Mobile)', 'frontend_react_native/', 'v1,v2,v3', 'v1', 2, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557431770', 'SITE000001', 'SITE000001', 'MOBILE', 'Android (Compose)', 'frontend_android/', 'v1,v2,v3', 'v1', 3, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557439967', 'SITE000001', 'SITE000001', 'MOBILE', 'iOS (SwiftUI)', 'frontend_ios/', 'v1,v2,v3', 'v1', 4, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557438248', 'SITE000001', 'SITE000001', 'FULLSTACK', 'Nuxt 4 + Prisma', 'fullstack_nuxt/', 'v1,v2,v3', 'v1', 1, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557438600', 'SITE000001', 'SITE000001', 'FULLSTACK', 'Next.js 15 + Prisma', 'fullstack_nextjs/', 'v1,v2,v3', 'v1', 2, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
INSERT INTO shopjoy_2604.md_sg_stack (stack_id, site_id, reg_site_id, category_cd, stack_nm, stack_prefix, version_list, default_version, sort_ord, use_yn, reg_by, reg_date, upd_by, upd_date) VALUES ('2608260557439348', 'SITE000001', 'SITE000001', 'ETC', 'DDL', 'ddl/', 'v1,v2,v3', 'v1', 1, 'Y', 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP);
