-- ============================================================
-- 단어사전 : 컬럼/테이블 약어 정의
-- ============================================================
--
-- ⚠️  상세 규칙 → _doc/정책서/931.ddl단어사전규칙.md  (단일 소스)
--
-- [ 핵심 요약 ]
--
-- PK       : 테이블명_id (복합 PK 금지)
-- 금액     : *_discnt_amt / refund_amt / cache_amt  (단독 amt 금지)
-- 수량     : order_qty / claim_qty / stock_qty      (단독 qty 금지)
-- 재고     : prod_stock / prod_opt_stock             (단독 stock 금지)
-- 가격     : list_price / sale_price / unit_price   (단독 price 금지)
-- 상태코드 : 테이블명_status_cd                     (단독 status 금지)
-- 설명     : entity_desc                             (단독 desc 금지)
-- 제목     : entity_title                            (단독 title 금지)
-- 내용     : entity_content                          (단독 content 금지)
-- 이름     : entity_nm  (name 대신 nm)
-- 결재     : appr_*     (approval 대신 appr)
-- 깊이     : entity_depth (단독 depth 금지)
-- 발신자   : sender_cd
--
-- [ 예외 ]
-- *_log 테이블 : ip, device, os, browser, token 등 단독 허용
-- *_hist 테이블 : 원본 컬럼명 + 단독어 추가 허용
--
-- [ 도메인 접두사 ]
-- sy_ 시스템  /  cm_ 커뮤니티  /  mb_ 회원
-- od_ 주문    /  pd_ 상품      /  pm_ 프로모션  /  dp_ 전시
-- ============================================================
