-- ============================================================
-- 단어사전 : 컬럼/테이블 약어 정의
-- 규칙: 약어는 소문자 snake_case 기준
-- ============================================================
--
-- [ 필수 명명 규칙 ]
--
-- 1. PRIMARY KEY: 항상 테이블명_id (UUID/TIMESTAMP+Random 형식)
--    예: site_id, user_id, order_id, code_grp_id, user_role_id
--    ⚠️ 복합 PK 금지, 필요시 UNIQUE INDEX로 구성
--    예: sy_user_role(user_role_id) + UNIQUE(user_id, role_id)
--
-- 2. 금액 관련: "금액" 으로 끝나는 설명 → _amt 서픽스 사용
--    예: 환불금액 → refund_amt, 할인금액 → discount_amt, 결재금액 → appr_amt
--    ⚠️ 단독 amt 금지 (반드시 복합어: discount_amt, refund_amt, cache_amt, balance_amt 등)
--
-- 2-1. 재고 관련: "재고" 으로 끝나는 설명 → _stock 서픽스 사용
--    예: 상품재고 → prod_stock, 옵션재고 → prod_opt_stock
--    ⚠️ 단독 stock 금지 (반드시 entity_stock 형식)
--
-- 3. 수량 관련: "수량" 으로 끝나는 설명 → _qty 서픽스 사용
--    예: 주문수량 → order_qty, 클레임수량 → claim_qty, 재고수량 → stock_qty
--    ⚠️ 단독 qty 금지 (반드시 복합어만 사용)
--
-- 4. 가격 관련: price 단독 사용 금지, 반드시 수식어 붙이기
--    예: list_price (정가), sale_price (판매가), unit_price (단가), item_price (소계)
--    ⚠️ 단독 price 금지
--
-- 5. 코드형 컬럼: 테이블명_status_cd 형식 (코드값 컬럼)
--    예: alarm_status_cd, order_status_cd, member_status_cd, prod_status_cd
--    패턴: [도메인_][엔티티_]상태명_cd
--    코드 테이블 PK: 테이블명_code (VARCHAR) - FK는 _cd 사용
--
-- 6. 설명 컬럼: description 대신 entity_desc 패턴 사용
--    예: product_desc, category_desc, coupon_desc, event_desc, area_desc (테이블명_desc 형식)
--    ⚠️ 단독 desc 금지 (반드시 entity_desc 형식)
--
-- 6-1. 제목/내용: title/content 단독 금지 → entity_title, entity_content 패턴
--    예: push_log_title, push_log_content, review_title, review_content, review_reply_content
--    ⚠️ 단독 title, content 금지
--
-- 6-2. 이름/전화/이메일/비밀번호/성별/주소/메모: name, phone, email, password, gender, addr, memo 단독 금지
--    예: member_nm, member_phone, member_email, member_password, member_gender, member_addr, member_zip_code, chatt_memo
--    예: user_nm, user_phone, user_email, user_password, user_gender, user_addr
--    ⚠️ 단독 name, phone, email, password, gender, addr, addr_detail, zip_code, memo 금지
--
-- 7. 결재 컬럼: approval 대신 appr 사용
--    예: appr_status_cd, appr_amt, appr_reason, appr_req_user_id, appr_aprv_user_id
--
-- 8. 계층/깊이: depth 대신 테이블명_depth 사용
--    예: category_depth (not depth)
--
-- 9. 발신자: sender 대신 sender_cd 사용 (코드형)
--    예: sender_cd (MEMBER/ADMIN)
--
-- ============================================================

-- 단어약어          한글명
-- ------------------------------------------------
-- id               아이디 (식별자)
-- nm               이름 / 명칭
-- cd               코드 (⚠️ 코드형 컬럼은 반드시 _cd로 끝나야 함, 테이블명_status_cd 형식: alarm_status_cd, order_status_cd, member_status_cd 등)
-- no               번호
-- yn               여부 (Y/N)
-- cnt              건수 / 개수
-- qty              수량 (⚠️ 단독사용 금지, 복합어만: order_qty, claim_qty, stock_qty 등)
-- amt              금액 (⚠️ 단독사용 금지, 복합어만: cache_amt, refund_amt, balance_amt, discount_amt 등)
-- price            가격 (⚠️ 단독사용 금지, 복합어만: list_price, sale_price, unit_price, item_price 등)
-- stock            재고 (⚠️ 단독사용 금지, 복합어만: prod_stock, prod_opt_stock 등)
-- title            제목 (⚠️ 단독사용 금지, 복합어만: event_title, notice_title, push_log_title, review_title 등)
-- content          내용 (⚠️ 단독사용 금지, 복합어만: event_content, push_log_content, review_content, blog_comment_content 등)
-- name             이름 (⚠️ 단독사용 금지, 복합어만: member_nm, prod_nm 등)
-- phone            전화 (⚠️ 단독사용 금지, 복합어만: member_phone, user_phone 등)
-- email            이메일 (⚠️ 단독사용 금지, 복합어만: member_email, user_email 등)
-- password         비밀번호 (⚠️ 단독사용 금지, 복합어만: member_password, user_password 등)
-- gender           성별 (⚠️ 단독사용 금지, 복합어만: member_gender, user_gender 등)
-- addr             주소 (⚠️ 단독사용 금지, 복합어만: member_addr, user_addr 등)
-- addr_detail      상세주소 (⚠️ 단독사용 금지, 복합어만: member_addr_detail, user_addr_detail 등)
-- zip_code         우편번호 (⚠️ 단독사용 금지, 복합어만: member_zip_code, user_zip_code 등)
-- memo             메모 (⚠️ 단독사용 금지, 복합어만: chatt_memo, order_memo 등)
-- subject          주제/제목 (⚠️ 단독사용 금지, 복합어만: template_subject, contact_subject 등)
-- answer           답변 (⚠️ 단독사용 금지, 복합어만: contact_answer, faq_answer 등)
-- remark           비고 (⚠️ 단독사용 금지, 복합어만: user_role_remark 등)
-- rate             비율 (%)
-- ord              순서 (정렬)
-- dt               일자 (DATE형)
-- date             일시 (TIMESTAMP형)
-- url              URL 경로
-- html             HTML 내용
-- ip               IP 주소 (⚠️ 예외: *_log 테이블은 단독 허용)
-- device           장치 (User-Agent) (⚠️ 예외: *_log 테이블은 단독 허용)
-- os               운영체제 (⚠️ 예외: *_log 테이블은 단독 허용)
-- browser          브라우저 (⚠️ 예외: *_log 테이블은 단독 허용)
-- country          국가 (⚠️ 예외: *_log 테이블은 단독 허용)
-- referrer         유입경로 URL (⚠️ 예외: *_log 테이블은 단독 허용)
-- token            토큰 (⚠️ 예외: *_log 테이블은 단독 허용)
-- access_token     액세스 토큰 (⚠️ 예외: *_log 테이블은 단독 허용)
-- refresh_token    리프레시 토큰 (⚠️ 예외: *_log 테이블은 단독 허용)
-- prev_token       이전 토큰 (⚠️ 예외: *_log 테이블은 단독 허용)
-- revoke_reason    폐기 사유 (⚠️ 예외: *_log 테이블은 단독 허용)
-- token_exp        토큰 만료일시 (⚠️ 예외: *_log 테이블은 단독 허용)
-- api_nm           API명 (⚠️ 예외: *_log 테이블은 단독 허용)
-- req_body         요청 본문 (⚠️ 예외: *_log 테이블은 단독 허용)
-- res_body         응답 본문 (⚠️ 예외: *_log 테이블은 단독 허용)
-- http_status      HTTP 상태코드 (⚠️ 예외: *_log 테이블은 단독 허용)
-- error_msg        오류 메시지 (⚠️ 예외: *_log 테이블은 단독 허용)
-- elapsed_ms       응답시간(ms) (⚠️ 예외: *_log 테이블은 단독 허용)
-- call_date        호출 일시 (⚠️ 예외: *_log 테이블은 단독 허용)
-- view_date        조회 일시 (⚠️ 예외: *_log 테이블은 단독 허용)
-- desc             설명 (⚠️ description 대신 사용하되, 반드시 entity_desc 형식: product_desc, category_desc 등)
-- content          본문 내용
-- title            제목
-- type             유형 (⚠️ 코드형이면 type_cd로: device_cd, etc)
-- status           상태 (⚠️ 코드형이면 status_cd로: alarm status_cd, batch status_cd 등)
-- result           결과 (⚠️ 코드형이면 result_cd로: login result_cd 등)
-- method           수단 / 방식 (⚠️ 코드형이면 method_cd로: HTTP method_cd 등)
-- grp              그룹
-- val              값
-- key              키
-- code             코드값 (문자)
-- info             정보
-- use              사용
-- reg              등록
-- upd              수정 / 업데이트
-- del              삭제
-- proc             처리
-- chg              변경
-- req              요청
-- res              응답
-- log              로그
-- hist             이력
-- snap             스냅샷
-- path             경로
-- disp_path        표시경로 (전시/프로퍼티 트리 빌드용 점(.) 구분 경로, 예: FRONT.모바일메인)
-- appr             결재 / 결재처리 (⚠️ approval 대신 appr 사용: appr_status_cd, appr_amt, appr_reason 등)
-- aprv             결재(승인) 약어 (appr_aprv_user_id, appr_aprv_date 등)
-- prop             프로퍼티 (환경설정/공통 파라미터)
-- target           대상
-- reason           사유
-- ------------------------------------------------
-- by               처리자 ID (sy_user.user_id 참조)
-- ------------------------------------------------

-- [ 도메인 접두사 ]
-- 단어약어          한글명
-- ------------------------------------------------
-- sy_              시스템 (공통/관리)
-- ec_              이커머스 (쇼핑몰)
-- ------------------------------------------------

-- [ 주요 엔티티 약어 ]
-- 단어약어          한글명
-- ------------------------------------------------
-- site             사이트
-- user             관리자 사용자
-- dept             부서
-- role             역할
-- menu             메뉴
-- brand            브랜드
-- vendor           업체 / 공급사
-- member           회원
-- prod             상품
-- category         카테고리
-- opt              옵션
-- sku              SKU (재고관리단위)
-- img              이미지
-- cart             장바구니
-- order            주문
-- order_item       주문상품
-- dliv             배송
-- claim            클레임 (취소/반품/교환)
-- coupon           쿠폰
-- issue            발급
-- usage            사용이력
-- cache            적립금
-- review           리뷰
-- media            미디어 (이미지/동영상)
-- reply            댓글
-- event            이벤트
-- notice           공지사항
-- contact          문의
-- chatt            채팅
-- disp             전시
-- panel            패널
-- widget           위젯
-- attach           첨부파일
-- batch            배치
-- alarm            알림
-- bbs              게시판
-- bbm              게시판 메시지
-- template         템플릿
-- code             공통코드
-- prop             프로퍼티 (sy_prop)
-- ------------------------------------------------

-- [ 주소/연락처 관련 ]
-- 단어약어          한글명
-- ------------------------------------------------
-- zip              우편번호
-- addr             주소
-- addr_detail      상세주소
-- phone            연락처 (전화번호)
-- email            이메일
-- recv             수령자 (수취인)
-- ------------------------------------------------

-- [ 금액/결제 관련 ]
-- 단어약어              한글명
-- ------------------------------------------------
-- list_price          정가 (원래가격)
-- unit_price          단가
-- sale_price          판매가
-- item_price          소계 (unit_price × order_qty)
-- total_purchase_amt  누적 구매금액
-- total_price         합계금액
-- pay_price           실결제금액
-- discount_amt        할인금액
-- coupon_discount_amt 쿠폰할인금액
-- refund_amt          환불금액
-- add_price           옵션 추가금액
-- min_order_amt       최소주문금액
-- max_discount_amt    최대할인한도
-- cache_amt           적립금 금액 (양수:적립/음수:사용)
-- balance_amt         잔액 (처리 후 계산 잔액)
-- cache_balance_amt   적립금 잔액 (누적)
-- pay_method          결제수단
-- ------------------------------------------------

-- [ 수량 관련 (복합어만 사용) ]
-- 단어약어              한글명
-- ------------------------------------------------
-- order_qty           주문 수량
-- claim_qty           클레임 수량
-- stock_qty           재고 수량
-- sale_cnt            판매 건수
-- ------------------------------------------------

-- [ 공통 코드 목록 ]
-- 코드그룹              코드값 예시
-- ------------------------------------------------
-- USER_STATUS          ACTIVE / INACTIVE / LOCKED
-- MEMBER_STATUS        ACTIVE / INACTIVE / WITHDRAWN / LOCKED
-- MEMBER_GRADE         BASIC / SILVER / GOLD / VIP
-- PRODUCT_STATUS       ACTIVE / INACTIVE / SOLDOUT / DELETED
-- ORDER_STATUS         PENDING / PAID / PREPARING / SHIPPED / DELIVERED / CANCELLED / REFUNDED
-- CLAIM_TYPE           CANCEL / RETURN / EXCHANGE
-- CLAIM_STATUS         REQUESTED / PROCESSING / COMPLETED / REJECTED
-- CLAIM_REASON         CHANGE_MIND / DEFECT / WRONG_ITEM / OTHER
-- COUPON_TYPE          RATE / FIXED
-- COUPON_STATUS        ACTIVE / INACTIVE / EXPIRED
-- CART_STATUS          ACTIVE / ORDERED / EXPIRED
-- REVIEW_STATUS        ACTIVE / HIDDEN / DELETED
-- REFUND_METHOD        CARD / ACCOUNT / CACHE
-- PAY_METHOD           CARD / ACCOUNT / CACHE / KAKAO / NAVER / TOSS
-- LOGIN_RESULT         SUCCESS / FAIL_PWD / FAIL_LOCKED / FAIL_NOT_FOUND
-- MEDIA_TYPE           IMAGE / VIDEO
-- DISP_AREA            (전시영역코드 — 사이트별 정의)
-- DISP_UI              (전시 UI 타입 — FRONT_MAIN/FRONT_PROD/FRONT_MY/MOBILE_MAIN/ADMIN_DASH 등)
-- DISP_STATUS          ACTIVE / INACTIVE
-- WIDGET_TYPE          image_banner / product_slider / product / cond_product / chart_bar / chart_line / chart_pie /
--                      text_banner / info_card / popup / file / file_list / coupon / html_editor /
--                      event_banner / cache_banner / widget_embed / barcode / countdown
-- VISIBILITY_TARGET    PUBLIC / MEMBER / VERIFIED / VIP / PREMIUM / GUEST 등 (^CODE^ 인코딩)
-- APPROVAL_STATUS      REQ / APPROVED / REJECTED / DONE
-- APPROVAL_TARGET      ORDER / PROD / DLIV / EXTRA
-- AUTH_METHOD          MAIN / SMS / OTP / AUTHENTICATOR
-- PROP_TYPE            STRING / NUMBER / BOOLEAN / JSON
-- ALARM_TYPE           PUSH / EMAIL / SMS / INAPP
-- ALARM_STATUS         DRAFT / SCHEDULED / SENT / FAILED
-- ------------------------------------------------
