#!/usr/bin/env node
/**
 * Capacitor 환경 적용 스크립트 (BO 앱).
 *
 * 사용법: node scripts/set-env.js [local|dev|prod]
 *
 * 동작:
 *   1) .env.{target} + .env.{target}.local 머지
 *   2) capacitor.config.ts 의 server.url 등 갱신
 *   3) www/env.js 자동 생성
 *
 * @see ShopjoyFoApp/scripts/set-env.js  FO 의 같은 파일 — 자세한 주석은 거기 참조
 */
const fs = require('fs');
const path = require('path');

/** local | dev | prod. */
const TARGET = (process.argv[2] || 'local').toLowerCase();

/** 앱 프로젝트 루트 (scripts/ 의 부모). */
const ROOT = path.resolve(__dirname, '..');

if (!['local', 'dev', 'prod'].includes(TARGET)) {
  console.error(`[set-env] 알 수 없는 환경: ${TARGET}. (local | dev | prod)`);
  process.exit(1);
}

/**
 * .env 파일 단순 KEY=VALUE 파서 (따옴표 제거 / 주석 무시).
 * @param {string} filename
 * @returns {Object<string, string>}
 */
function loadEnvFile(filename) {
  const filePath = path.join(ROOT, filename);
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, 'utf8');
  const env = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

// 1) 환경 파일 로드 + 머지 (.env.{target} + .env.{target}.local).
const baseEnv = loadEnvFile(`.env.${TARGET}`);
const localOverride = loadEnvFile(`.env.${TARGET}.local`);
const env = { ...baseEnv, ...localOverride };

if (Object.keys(env).length === 0) {
  console.error(`[set-env] .env.${TARGET} 파일을 찾을 수 없거나 비어있습니다.`);
  process.exit(1);
}

// 2) capacitor.config.ts 갱신 (server.url / cleartext / androidScheme).
const cfgPath = path.join(ROOT, 'capacitor.config.ts');
let src = fs.readFileSync(cfgPath, 'utf8');

/** WebView 가 로드할 BO URL — 보통 `/bo.html` 포함. */
const url = env.BASE_URL || 'http://10.0.2.2:5501/bo.html';
const cleartext = env.CLEARTEXT === 'true';
const androidScheme = env.ANDROID_SCHEME || (cleartext ? 'http' : 'https');

src = src.replace(/url:\s*'[^']*'/, `url: '${url}'`);
src = src.replace(/cleartext:\s*(true|false)/, `cleartext: ${cleartext}`);
src = src.replace(/androidScheme:\s*'[^']*'/, `androidScheme: '${androidScheme}'`);
fs.writeFileSync(cfgPath, src, 'utf8');

// 3) www/env.js 자동 생성.
const wwwEnvPath = path.join(ROOT, 'www', 'env.js');
const wwwEnv = `// AUTO-GENERATED by scripts/set-env.js — do not edit
window.__APP_ENV__ = ${JSON.stringify(env, null, 2)};
window.__APP_ENV_NAME__ = '${TARGET}';
`;
fs.writeFileSync(wwwEnvPath, wwwEnv, 'utf8');

// 4) 결과 출력.
console.log(`[set-env] ${TARGET.toUpperCase()} 적용 완료`);
console.log(`         APP_NAME       = ${env.APP_NAME || '(unset)'}`);
console.log(`         BASE_URL       = ${url}`);
console.log(`         CLEARTEXT      = ${cleartext}`);
console.log(`         ANDROID_SCHEME = ${androidScheme}`);
console.log(`         (loaded from   .env.${TARGET}${fs.existsSync(path.join(ROOT, '.env.' + TARGET + '.local')) ? ' + .env.' + TARGET + '.local' : ''})`);
console.log(`         (www/env.js    ${Object.keys(env).length} keys)`);
