-- ============================================================================
-- dp_widget_lib: 디스플레이 위젯 라이브러리 샘플 데이터
-- 정책 참조: _doc/정책서/ec/dp/dp.07.전시WidgetLib.md
-- 위젯코드: 전역 UNIQUE, {DOMAIN}_{TYPE}_{DESCRIPTION} 형식
-- is_system='Y': 시스템 기본 위젯 (삭제 제한), site_id=NULL: 공통 라이브러리
-- 위젯유형(WIDGET_TYPE) 19종: image_banner, product_slider, product, cond_product,
--   chart_bar, chart_line, chart_pie, text_banner, info_card, popup, file, file_list,
--   coupon, html_editor, event_banner, cache_banner, widget_embed, barcode, countdown
-- ============================================================================

-- ======================================================================
-- 시스템 표준 위젯 라이브러리 (is_system='Y', site_id=NULL 공통)
-- ======================================================================
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000001', NULL, 'STD_BANNER_MAIN', '표준 메인배너', 'image_banner', '메인 화면 풀너비 이미지 배너 - 모바일/PC 분리 이미지 지원', 'std.banner', 'https://cdn.shopjoy.com/widget/thumb/std_banner_main.jpg', '<a href="{{link_url}}" target="{{link_target}}"><img src="{{img_url}}" alt="{{alt}}" class="banner-main"/></a>', '{"type":"object","properties":{"img_url":{"type":"string","title":"PC이미지URL"},"mobile_img_url":{"type":"string","title":"모바일이미지URL"},"link_url":{"type":"string","title":"링크URL"},"link_target":{"type":"string","title":"타겟","enum":["_self","_blank"],"default":"_self"},"alt":{"type":"string","title":"대체텍스트"}},"required":["img_url"]}', 'Y', 1, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000002', NULL, 'STD_PROD_SLIDER', '표준 상품 슬라이더', 'product_slider', '카테고리/상품ID 기준 가로 슬라이드 상품 노출', 'std.product', 'https://cdn.shopjoy.com/widget/thumb/std_prod_slider.jpg', '<div class="prod-slider" data-category="{{category_id}}" data-count="{{slide_count}}"></div>', '{"type":"object","properties":{"title":{"type":"string","title":"타이틀"},"category_id":{"type":"string","title":"카테고리ID"},"slide_count":{"type":"integer","title":"한 슬라이드 표시수","default":4},"auto_play":{"type":"boolean","default":true}}}', 'Y', 2, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000003', NULL, 'STD_PROD_BEST', '표준 베스트셀러', 'cond_product', '판매량 기준 자동 베스트셀러 노출 (최근 N일)', 'std.product', 'https://cdn.shopjoy.com/widget/thumb/std_prod_best.jpg', '<div class="prod-best" data-condition="BEST_SELLER" data-period="{{period_days}}"></div>', '{"type":"object","properties":{"limit":{"type":"integer","default":8},"period_days":{"type":"integer","default":7},"sort":{"type":"string","default":"sale_cnt_desc"}}}', 'Y', 3, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000004', NULL, 'STD_PROD_NEW', '표준 신상품', 'cond_product', '최근 등록된 신상품 자동 노출', 'std.product', 'https://cdn.shopjoy.com/widget/thumb/std_prod_new.jpg', '<div class="prod-new" data-condition="NEW_ARRIVAL"></div>', '{"type":"object","properties":{"limit":{"type":"integer","default":8},"period_days":{"type":"integer","default":30}}}', 'Y', 4, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000005', NULL, 'STD_PROD_DISCOUNT', '표준 할인특가', 'cond_product', '할인율 높은순 자동 노출', 'std.product', 'https://cdn.shopjoy.com/widget/thumb/std_prod_discount.jpg', '<div class="prod-discount" data-condition="HIGH_DISCOUNT"></div>', '{"type":"object","properties":{"limit":{"type":"integer","default":6},"min_discount_rate":{"type":"integer","default":20}}}', 'Y', 5, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000006', NULL, 'STD_TEXT_BANNER', '표준 텍스트 배너', 'text_banner', '이미지 없는 텍스트 전용 배너 - 무료배송/공지 등', 'std.banner', 'https://cdn.shopjoy.com/widget/thumb/std_text_banner.jpg', '<div class="text-banner" style="background:{{bg_color}};color:{{text_color}}"><span>{{icon}}</span> {{text}} <small>{{sub_text}}</small></div>', '{"type":"object","properties":{"text":{"type":"string","title":"본문"},"sub_text":{"type":"string","title":"부가문구"},"bg_color":{"type":"string","default":"#fff0f4"},"text_color":{"type":"string","default":"#c0396a"},"icon":{"type":"string","title":"아이콘이모지"},"link_url":{"type":"string"}},"required":["text"]}', 'Y', 6, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000007', NULL, 'STD_INFO_CARD', '표준 정보카드', 'info_card', '아이콘+제목+설명 형식 정보카드 (당일출고/AS안내 등)', 'std.info', 'https://cdn.shopjoy.com/widget/thumb/std_info_card.jpg', '<div class="info-card"><i>{{icon}}</i><h4>{{title}}</h4><p>{{content}}</p></div>', '{"type":"object","properties":{"icon":{"type":"string"},"title":{"type":"string"},"content":{"type":"string"},"link_url":{"type":"string"}}}', 'Y', 7, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000008', NULL, 'STD_POPUP_NOTICE', '표준 공지 팝업', 'popup', '진입 시 자동 노출되는 공지/이벤트 팝업 (쿠키 기반 오늘하루안보기)', 'std.popup', 'https://cdn.shopjoy.com/widget/thumb/std_popup.jpg', '<div class="popup-layer" data-cookie="{{cookie_key}}"><img src="{{img_url}}"/><a href="{{link_url}}">{{title}}</a></div>', '{"type":"object","properties":{"title":{"type":"string"},"img_url":{"type":"string"},"link_url":{"type":"string"},"close_label":{"type":"string","default":"오늘 하루 안 보기"},"cookie_key":{"type":"string"},"cookie_days":{"type":"integer","default":1}}}', 'Y', 8, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000009', NULL, 'STD_COUPON_BTN', '표준 쿠폰 발급버튼', 'coupon', '단일 쿠폰 즉시 발급 버튼 위젯', 'std.coupon', 'https://cdn.shopjoy.com/widget/thumb/std_coupon.jpg', '<button class="coupon-btn" data-coupon="{{coupon_id}}">{{btn_label}}</button>', '{"type":"object","properties":{"coupon_id":{"type":"string"},"btn_label":{"type":"string"},"desc":{"type":"string"},"expire_days":{"type":"integer"}},"required":["coupon_id"]}', 'Y', 9, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000010', NULL, 'STD_HTML_EDITOR', '표준 HTML 에디터', 'html_editor', '관리자가 직접 HTML 작성하는 자유형식 위젯', 'std.custom', 'https://cdn.shopjoy.com/widget/thumb/std_html.jpg', '{{html}}', '{"type":"object","properties":{"html":{"type":"string","title":"HTML내용"},"css":{"type":"string","title":"CSS"}}}', 'Y', 10, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000011', NULL, 'STD_COUNTDOWN', '표준 카운트다운', 'countdown', '행사 종료까지 남은 시간 실시간 카운트다운 표시', 'std.timer', 'https://cdn.shopjoy.com/widget/thumb/std_countdown.jpg', '<div class="countdown" data-target="{{target_datetime}}"><span>{{label}}</span></div>', '{"type":"object","properties":{"target_datetime":{"type":"string","format":"date-time"},"label":{"type":"string"},"finished_msg":{"type":"string"},"show_days":{"type":"boolean","default":true}}}', 'Y', 11, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000012', NULL, 'STD_EVENT_BANNER', '표준 이벤트 배너', 'event_banner', 'pm_event 연동 이벤트 배너 (카운트다운 옵션 포함)', 'std.event', 'https://cdn.shopjoy.com/widget/thumb/std_event_banner.jpg', '<a href="/event/{{event_id}}" class="event-banner"><img src="{{img_url}}"/></a>', '{"type":"object","properties":{"event_id":{"type":"string"},"img_url":{"type":"string"},"show_countdown":{"type":"boolean","default":false}},"required":["event_id"]}', 'Y', 12, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000013', NULL, 'STD_CACHE_BANNER', '표준 캐시 충전배너', 'cache_banner', 'pm_cache 충전 프로모션 배너', 'std.cache', 'https://cdn.shopjoy.com/widget/thumb/std_cache_banner.jpg', '<a href="{{link_url}}" class="cache-banner"><img src="{{img_url}}"/><span>{{title}}</span></a>', '{"type":"object","properties":{"cache_promo_id":{"type":"string"},"title":{"type":"string"},"img_url":{"type":"string"},"link_url":{"type":"string"}}}', 'Y', 13, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000014', NULL, 'STD_CHART_BAR', '표준 막대차트 (관리자)', 'chart_bar', '관리자 대시보드 막대 그래프 통계 위젯', 'std.chart', 'https://cdn.shopjoy.com/widget/thumb/std_chart_bar.jpg', '<div class="chart-bar" data-api="{{data_api}}"></div>', '{"type":"object","properties":{"title":{"type":"string"},"data_api":{"type":"string"},"x_field":{"type":"string"},"y_field":{"type":"string"},"color":{"type":"string","default":"#ec4899"}}}', 'Y', 14, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000015', NULL, 'STD_CHART_LINE', '표준 라인차트 (관리자)', 'chart_line', '관리자 대시보드 라인 그래프 통계 위젯', 'std.chart', 'https://cdn.shopjoy.com/widget/thumb/std_chart_line.jpg', '<div class="chart-line" data-api="{{data_api}}"></div>', '{"type":"object","properties":{"title":{"type":"string"},"data_api":{"type":"string"},"x_field":{"type":"string"},"y_field":{"type":"string"}}}', 'Y', 15, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000016', NULL, 'STD_CHART_PIE', '표준 파이차트 (관리자)', 'chart_pie', '관리자 대시보드 파이 그래프 통계 위젯', 'std.chart', 'https://cdn.shopjoy.com/widget/thumb/std_chart_pie.jpg', '<div class="chart-pie" data-api="{{data_api}}"></div>', '{"type":"object","properties":{"title":{"type":"string"},"data_api":{"type":"string"},"label_field":{"type":"string"},"value_field":{"type":"string"}}}', 'Y', 16, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000017', NULL, 'STD_FILE_DOWNLOAD', '표준 파일 다운로드', 'file', '단일 파일 다운로드 링크 위젯', 'std.file', 'https://cdn.shopjoy.com/widget/thumb/std_file.jpg', '<a href="{{file_url}}" download class="file-dl">{{btn_label}} ({{file_size}})</a>', '{"type":"object","properties":{"file_nm":{"type":"string"},"file_url":{"type":"string"},"file_size":{"type":"string"},"btn_label":{"type":"string","default":"다운로드"}}}', 'Y', 17, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000018', NULL, 'STD_FILE_LIST', '표준 파일 목록', 'file_list', '여러 파일 리스트 표시 위젯 (자료실/약관)', 'std.file', 'https://cdn.shopjoy.com/widget/thumb/std_file_list.jpg', '<ul class="file-list">{{#files}}<li><a href="{{url}}">{{nm}}</a></li>{{/files}}</ul>', '{"type":"object","properties":{"title":{"type":"string"},"files":{"type":"array","items":{"type":"object","properties":{"nm":{"type":"string"},"url":{"type":"string"}}}}}}', 'Y', 18, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000019', NULL, 'STD_BARCODE', '표준 바코드/QR', 'barcode', '바코드 또는 QR 코드 표시 위젯', 'std.barcode', 'https://cdn.shopjoy.com/widget/thumb/std_barcode.jpg', '<div class="barcode" data-type="{{type}}" data-value="{{value}}"></div>', '{"type":"object","properties":{"type":{"type":"string","enum":["QR","CODE128","EAN13"]},"value":{"type":"string"},"size":{"type":"integer","default":200},"label":{"type":"string"}}}', 'Y', 19, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604190900000020', NULL, 'STD_WIDGET_EMBED', '표준 위젯 임베드', 'widget_embed', '다른 위젯을 현 위치에 재사용 임베드', 'std.embed', 'https://cdn.shopjoy.com/widget/thumb/std_embed.jpg', '<div class="widget-embed" data-widget="{{embed_widget_id}}"></div>', '{"type":"object","properties":{"embed_widget_id":{"type":"string"},"fallback":{"type":"string"}},"required":["embed_widget_id"]}', 'Y', 20, 'Y', 'SYSTEM', '2026-04-19 09:00:00.000', NULL, NULL);

-- ======================================================================
-- 사이트01 전용 위젯 라이브러리 (베이지/카키 톤)
-- ======================================================================
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000001', '01', 'SITE01_BANNER_TOP', '사이트01 상단배너', 'image_banner', '사이트01 메인 상단 풀너비 배너 (베이지 톤)', 'site01.banner', 'https://cdn.shopjoy.com/widget/thumb/site01_banner_top.jpg', '<div class="site01-banner"><img src="{{img_url}}"/></div>', '{"type":"object","properties":{"img_url":{"type":"string"},"link_url":{"type":"string"}}}', 'N', 1, 'Y', 'admin01', '2026-04-20 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000002', '01', 'SITE01_PROD_FEATURED', '사이트01 추천상품', 'product_slider', '사이트01 메인 추천 상품 슬라이더', 'site01.product', 'https://cdn.shopjoy.com/widget/thumb/site01_prod_featured.jpg', '<div class="site01-prod-slider"></div>', '{"type":"object","properties":{"category_id":{"type":"string"},"slide_count":{"type":"integer","default":4}}}', 'N', 2, 'Y', 'admin01', '2026-04-20 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000003', '01', 'SITE01_COUPON_VIP', '사이트01 VIP쿠폰', 'coupon', '사이트01 VIP 회원 전용 쿠폰 발급 위젯', 'site01.coupon', 'https://cdn.shopjoy.com/widget/thumb/site01_coupon_vip.jpg', '<button class="vip-coupon">{{btn_label}}</button>', '{"type":"object","properties":{"coupon_id":{"type":"string"},"btn_label":{"type":"string","default":"VIP 쿠폰 받기"}}}', 'N', 3, 'Y', 'admin01', '2026-04-20 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000004', '01', 'SITE01_HERO_BIG', '사이트01 히어로배너', 'image_banner', '사이트01 메인 대형 히어로 배너', 'site01.banner', 'https://cdn.shopjoy.com/widget/thumb/site01_hero.jpg', '<div class="site01-hero"></div>', '{"type":"object","properties":{"img_url":{"type":"string"},"mobile_img_url":{"type":"string"}}}', 'N', 4, 'Y', 'admin01', '2026-04-20 09:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000005', '01', 'SITE01_BRAND_STORY', '사이트01 브랜드스토리', 'html_editor', '사이트01 브랜드 소개 HTML 위젯', 'site01.brand', 'https://cdn.shopjoy.com/widget/thumb/site01_brand.jpg', '<section class="brand-story">{{html}}</section>', '{"type":"object","properties":{"html":{"type":"string"}}}', 'N', 5, 'Y', 'admin01', '2026-04-20 09:00:00.000', NULL, NULL);

-- ======================================================================
-- 사이트02 전용 위젯 라이브러리 (민트 그린 톤)
-- ======================================================================
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000011', '02', 'SITE02_BANNER_MAIN', '사이트02 메인배너', 'image_banner', '사이트02 메인 배너 (민트 그린 톤)', 'site02.banner', 'https://cdn.shopjoy.com/widget/thumb/site02_banner.jpg', '<div class="site02-banner"></div>', '{"type":"object","properties":{"img_url":{"type":"string"}}}', 'N', 1, 'Y', 'admin02', '2026-04-20 10:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000012', '02', 'SITE02_PROD_GREEN', '사이트02 친환경상품', 'cond_product', '사이트02 친환경 카테고리 상품 자동 노출', 'site02.product', 'https://cdn.shopjoy.com/widget/thumb/site02_prod_green.jpg', '<div class="site02-eco"></div>', '{"type":"object","properties":{"category_id":{"type":"string"},"limit":{"type":"integer","default":6}}}', 'N', 2, 'Y', 'admin02', '2026-04-20 10:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000013', '02', 'SITE02_EVENT_SPRING', '사이트02 봄이벤트', 'event_banner', '사이트02 봄 시즌 이벤트 배너', 'site02.event', 'https://cdn.shopjoy.com/widget/thumb/site02_event_spring.jpg', '<a class="site02-event"></a>', '{"type":"object","properties":{"event_id":{"type":"string"},"img_url":{"type":"string"}}}', 'N', 3, 'Y', 'admin02', '2026-04-20 10:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000014', '02', 'SITE02_INFO_DLIV', '사이트02 배송안내', 'info_card', '사이트02 친환경 배송 안내 카드', 'site02.info', 'https://cdn.shopjoy.com/widget/thumb/site02_info_dliv.jpg', '<div class="site02-info"></div>', '{"type":"object","properties":{"icon":{"type":"string"},"title":{"type":"string"},"content":{"type":"string"}}}', 'N', 4, 'Y', 'admin02', '2026-04-20 10:00:00.000', NULL, NULL);

-- ======================================================================
-- 사이트03 전용 위젯 라이브러리 (로얄 퍼플 럭셔리)
-- ======================================================================
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000021', '03', 'SITE03_HERO_LUXE', '사이트03 럭셔리히어로', 'image_banner', '사이트03 럭셔리 히어로 배너 (로얄 퍼플)', 'site03.banner', 'https://cdn.shopjoy.com/widget/thumb/site03_hero.jpg', '<div class="site03-hero-luxe"></div>', '{"type":"object","properties":{"img_url":{"type":"string"}}}', 'N', 1, 'Y', 'admin03', '2026-04-20 11:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000022', '03', 'SITE03_PROD_PREMIUM', '사이트03 프리미엄상품', 'product_slider', '사이트03 프리미엄 라인 상품 슬라이더', 'site03.product', 'https://cdn.shopjoy.com/widget/thumb/site03_prod_premium.jpg', '<div class="site03-premium"></div>', '{"type":"object","properties":{"prod_ids":{"type":"array"}}}', 'N', 2, 'Y', 'admin03', '2026-04-20 11:00:00.000', NULL, NULL);
INSERT INTO shopjoy_2604.dp_widget_lib VALUES ('WL2604200900000023', '03', 'SITE03_VIP_LOUNGE', '사이트03 VIP라운지', 'html_editor', '사이트03 VIP 회원 전용 라운지 안내 HTML', 'site03.vip', 'https://cdn.shopjoy.com/widget/thumb/site03_vip.jpg', '<section class="vip-lounge">{{html}}</section>', '{"type":"object","properties":{"html":{"type":"string"}}}', 'N', 3, 'Y', 'admin03', '2026-04-20 11:00:00.000', NULL, NULL);
